### ISSUE TITLE
Source code release

### ISSUE THREAD

**Issue by baotonglu** [HNUSystemsLab/HashEvaluation#1]
When will the source code be released?

**Comment by DaokunHu** [comment]
We will open source immediately when the paper is published.
@baotonglu

**Comment by baotonglu** [comment]
The [paper](https://vldb.org/pvldb/vol14/p785-chen.pdf) is already published.

**Comment by DaokunHu** [comment]
The source code will be released in two days.
@baotonglu

**Comment by baotonglu** [comment]
Thanks.
