### ISSUE TITLE
Questions about the results of figures

### ISSUE THREAD

**Issue by amyzx** [HNUSystemsLab/HashEvaluation#3]
Hi, thanks for sharing your source code. 

I am trying to redo your experiment. But I found my results is different from your results shown in your paper. Would you mind sharing your shell scripts for generating the results of all figures shown in your paper? 

For example, as for Fig 3 a, I almost always get zero for the amount of read/write bytes per operation.  
As for Fig 3 b, I could not find how to count the amount of CLWB and FENCE instructions. 
As for Fig 4 a, I got the following result. It seems these throughputs are larger than your results.
For Level hashing, I got segment fault when running 48 and 64 threads. 
And for Dash, clevel, I could not get the final result and the program will be killed.

![image](https://user-images.githubusercontent.com/8285571/128653909-8fa2cb20-ff7d-4ec6-950f-9a40b3f7dbed.png)

![image](https://user-images.githubusercontent.com/8285571/128653893-82e67b8f-51e5-48bc-bb1f-1dd6f309925e.png)

The following is my shell script for insert, pos read, neg read and delete for single thread.
sudo ./PiBench ./CCEH.so -S 16777216 -p 200000000 -M THROUGHPUT
sudo ./PiBench ./CCEH.so --skip_load=false -S 16777216 -p 200000000  -r 1.0 -i 0  -M THROUGHPUT
sudo ./PiBench ./CCEH.so --skip_load=false -S 16777216 -p 200000000  -r 1.0 -i 0 -N 1.0 -M THROUGHPUT
sudo ./PiBench ./CCEH.so --skip_load=false -S 16777216 -p 200000000  -d 1.0 -i 0  -M THROUGHPUT

And this is my computer setting.
![image](https://user-images.githubusercontent.com/8285571/128654569-1b2985e3-5077-431c-a92b-bc2b744c14ca.png)

Looking forward to your reply. Thanks!

**Comment by DaokunHu** [comment]
Q1: "Fig 3 a, I almost always get zero for the amount of read/write bytes per operation"
A: Did you change the location of PM filesystem mount point in "hash/common/Makefile_common"
> PFLAGS := -DPMEM_LOC="\"/mnt/pmem\""

Q2："Fig 3 b, I could not find how to count the amount of CLWB and FENCE instructions."
A: This source code does not include the code for counting the amount of CLWB and FENCE instructions.

Q3： Fig 4 a, I got the following result. It seems these throughputs are larger than your results.
A:  Please check Q1 first.

Q4: For Level hashing, I got segment fault when running 48 and 64 threads.
A: Sorry. Can you offer more information about the segment error, such as the location of the segment error?

Q5:  for Dash, clevel, I could not get the final result and the program will be killed.
A: Try to run it with a smaller scale, for instance, with -P 20000000.

@amyzx

**Comment by amyzx** [comment]
Hi, @daokunhu, thanks for your quick reply!

Q1: I have set `PFLAGS := -DPMEM_LOC="\"/mnt/pmem1/zx-hash\""`   which is a directory that I created to store my hash data. Should it have to be the root directory for PM filesystem (like /mnt/pmem1 you mentioned)?

Q2: Could you briefly explain how you count the amount of CLWB and FENCE instructions? 

Q3: I am not sure whether this is due to different experimental settings. My server has only one socket, which contains 16 cores. 

Q4 and Q5: I will redo Level's experiment to record the results, and also run with a smaller scale for Dash and clevel. 

By the way, do you think my commands are correct?

**Comment by DaokunHu** [comment]
Hello,@amyzx!
A1: Your path is valid.
A2: We count the CLWB and FENCE instructions by adding a counting variable after each CLWB and FENCE. This variable will incur extra overhead, so we do not keep it in this source code, and FENCE and CLWB almost have no influence among these hash indexes.
A3: Thus, with Hyper-Threading, 32 threads are enough.

Your commands seem good. About "get zero for the amount of read/write bytes per operation", try with `-M PM` rather than `-M THROUGHPUT`

**Comment by amyzx** [comment]
@daokunhu  Thanks for your reply! I still have three questions.

**1. The memory used in hash methods.** 

In your summary for 6 hash methods, only SOFT is DRAM+PM. Do you mean the other 5 hash methods only use PM memory? That is, data structures of hash tables are allocated by `vmem_aligned_alloc` in PM and operations are also done in PM. 

However, I find the meaning for clflush instruction is to flush cache data to main memory. Does this means hash table operations are done in DRAM? This makes me feel confused. 

**2. The discussion about small random PM writes restrict the performance of hash tables.**

Is there any way to obtain small random writes phenomenon? I am wondering how you evaluate random small writes' effects for hash tables.

**3. The NUMA function.**

In your experiment, you measured the impact of NUMA achitecture on throughput. Could you explain the instructions or shells you used? 

In addition, I find libvmem is no longer actively developed and lacks certain features of memkind such as [NUMA awareness](https://pmem.io/vmem/manpages/linux/master/libvmem/libvmem.7.html). 

I am a new beginner and have little knowledge about PM. Looking forward to your reply. Thanks!

**Comment by DaokunHu** [comment]
Hello @amyzx !
Q1:  Do the other 5 hash methods only use PM memory?
A: The data(key-value pairs) and data structure(hash table) are persisted on PM. Spaces allocated by PM allocator are stored on PM.   Temporary variables are still stored in DRAM. 
If the address is pointed to PM, then the CLFLUSH instruction flushes cache data into PM.
[pdf](https://www.usenix.org/system/files/login/articles/08_rudoff_040-045_final.pdf) and [pdf](https://www.usenix.org/system/files/login/articles/login_summer17_07_rudoff.pdf) may help you understand.

A2: You can write some small-sized data into an array on PM in a random way or a sequence way to obtain the difference. We also constructed a simple array model to evaluate the influence of small write.

A3: The only tool we used is `numactl`. `libvmem` is only for test and evaluation. If you want a real PM application, you should use `libpmem` or `libpmemobj` or `libpmemobj++`.

**Comment by amyzx** [comment]
@daokunhu  Thanks for your detailed reply!
