### ISSUE TITLE
Some questions about the resizing time measurement

### ISSUE THREAD

**Issue by Assembles** [HNUSystemsLab/HashEvaluation#4]
Hi! Recently, I'm trying to redo your experiments, but I encountered difficulties in some parts. Would you mind giving me some tips on how to solve these problems?

First, in the figure 8, for CCEH and Dash, they both have segment splitting and directory doubling time, but I have no idea how to measure them. Could you tell me how did you design this part?

Second, in the figure 9, how can I use pcm to measure the allocator time?

Looking forward to your reply. Thank you.

**Comment by DaokunHu** [comment]
Thanks for your attention!
Our source code does not support measure the splitting and doubling time directly. A simple way is to count the time for each splitting and doubling with a timer. The PCM can not measure the time of allocation. You need a timer to count each allocation time. 
@Assembles
